-- =====================================================================
-- KỊCH BẢN KHỞI TẠO CƠ SỞ DỮ LIỆU TOÀN DIỆN
-- Database: AITradingDB_v1
-- Last Updated: 2026-06-25 (Đã cập nhật bảng AI riêng biệt)
-- =====================================================================

-- Bỏ comment 3 dòng dưới nếu bạn chưa tạo Database
-- CREATE DATABASE AITradingDB_v1;
-- GO
-- USE AITradingDB_v1;
-- GO

-- =====================================================================
-- BƯỚC 1: KIỂM TRA VÀ XÓA CÁC BẢNG CŨ NẾU TỒN TẠI
-- =====================================================================
DROP TABLE IF EXISTS __EFMigrationsHistory;
DROP TABLE IF EXISTS AiOrders;
DROP TABLE IF EXISTS AiTradePositions;
DROP TABLE IF EXISTS AiStockTransactions;
DROP TABLE IF EXISTS AiTradeEpisodes;
DROP TABLE IF EXISTS StockTransactions;
DROP TABLE IF EXISTS TradeEpisodes;
DROP TABLE IF EXISTS TradePositions;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS TradingStrategies;
DROP TABLE IF EXISTS UserPreferences;
DROP TABLE IF EXISTS Assets;
GO

-- =====================================================================
-- BƯỚC 2: TẠO BẢNG DỮ LIỆU NGƯỜI DÙNG (USER DATA)
-- =====================================================================

-- Bảng danh sách cổ phiếu
CREATE TABLE Assets (
	Symbol NVARCHAR(450) PRIMARY KEY,
	Exchange NVARCHAR(MAX) NOT NULL,
	CompanyName NVARCHAR(MAX) NOT NULL
);
GO

-- Bảng lệnh của người dùng
CREATE TABLE Orders (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Symbol NVARCHAR(MAX) NOT NULL,
	OrderType NVARCHAR(MAX) NOT NULL,
	Quantity INT NOT NULL,
	Price DECIMAL(18,4) NOT NULL,
	OrderDate DATETIME2 NOT NULL,
	Status NVARCHAR(MAX) NOT NULL,
	Rationale NVARCHAR(MAX) NOT NULL
);
GO

-- Bảng vị thế giao dịch của người dùng
CREATE TABLE TradePositions (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Symbol NVARCHAR(MAX) NOT NULL,
	Quantity INT NOT NULL,
	EntryPrice DECIMAL(18,4) NOT NULL,
	ExitPrice DECIMAL(18,4) NULL,
	EntryDate DATETIME2 NOT NULL,
	ExitDate DATETIME2 NULL,
	Status NVARCHAR(MAX) NOT NULL,
	PnL DECIMAL(18,4) NOT NULL,
	StopLossPrice DECIMAL(18,4) NULL,
	TakeProfitPrice DECIMAL(18,4) NULL,
	TargetProfitAmount DECIMAL(18,4) NULL,
	InvestedAmount DECIMAL(18,4) NULL,
	BudgetAmount DECIMAL(18,4) NULL,
	ExpectedHoldDays INT NULL
);
GO

-- Bảng bài học kinh nghiệm người dùng
CREATE TABLE TradeEpisodes (
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	MarketContext NVARCHAR(MAX) NOT NULL,
	ActionTaken NVARCHAR(MAX) NOT NULL,
	Rationale NVARCHAR(MAX) NOT NULL,
	Result NVARCHAR(MAX) NOT NULL,
	LessonLearned NVARCHAR(MAX) NOT NULL,
	Timestamp DATETIME2 NOT NULL
);
GO

-- Bảng chi tiết giao dịch người dùng (từng lệnh MUA/BÁN)
CREATE TABLE StockTransactions (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Symbol NVARCHAR(MAX) NOT NULL,
	TransactionType NVARCHAR(10) NOT NULL,
	Quantity INT NOT NULL,
	Price DECIMAL(18,4) NOT NULL,
	TransactionDate DATETIME2 NOT NULL,
	Fee DECIMAL(18,4) NULL,
	TotalAmount DECIMAL(18,4) NOT NULL DEFAULT 0,
	PnlAmount DECIMAL(18,4) NULL,
	Source NVARCHAR(50) NOT NULL DEFAULT 'DNSE',
	PositionId INT NULL,
	Notes NVARCHAR(MAX) NULL,
	PriceHighSinceBuy DECIMAL(18,4) NULL,
	PriceLowSinceBuy DECIMAL(18,4) NULL,
	TimingScore DECIMAL(18,4) NULL
);
GO

-- =====================================================================
-- BƯỚC 3: TẠO BẢNG CẤU HÌNH VÀ CHIẾN LƯỢC
-- =====================================================================

-- Bảng cấu hình người dùng
CREATE TABLE UserPreferences (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	InvestmentHorizon NVARCHAR(MAX) NOT NULL,
	TargetProfitPercentage DECIMAL(18,4) NOT NULL,
	MaxLossPercentage DECIMAL(18,4) NOT NULL,
	AmountPerTrade DECIMAL(18,4) NOT NULL,
	RiskPerTrade DECIMAL(18,4) NOT NULL DEFAULT 0,
	TargetStartDate DATETIME2 NOT NULL DEFAULT GETDATE(),
	TargetAmount DECIMAL(18,4) NOT NULL,
	TakeProfitAmount DECIMAL(18,4) NOT NULL,
	StopLossAmount DECIMAL(18,4) NOT NULL,
	RiskTolerance NVARCHAR(MAX) NOT NULL,
	DnseUsername NVARCHAR(MAX) NOT NULL DEFAULT '',
	DnsePassword NVARCHAR(MAX) NOT NULL DEFAULT '',
	DnseToken NVARCHAR(MAX) NOT NULL DEFAULT ''
);
GO

-- Bảng thư viện chiến lược giao dịch
CREATE TABLE TradingStrategies (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(MAX) NOT NULL,
	StrategyType NVARCHAR(MAX) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	RuleLogic NVARCHAR(MAX) NOT NULL,
	IsAutoGenerated BIT NOT NULL DEFAULT 0,
	LearnCount INT NOT NULL DEFAULT 0,
	WinCount INT NOT NULL DEFAULT 0,
	LossCount INT NOT NULL DEFAULT 0,
	LastLearnedAt DATETIME2 NULL
);
GO

-- Nạp dữ liệu chiến lược nền tảng
INSERT INTO TradingStrategies (Name, StrategyType, Description, RuleLogic)
VALUES 
(
	N'RSI Quá mua / Quá bán (RSI Overbought/Oversold)',
	N'Indicator',
	N'Chỉ số sức mạnh tương đối (RSI) đo lường động lượng giá. RSI dưới 30 báo hiệu quá bán (rẻ), trên 70 báo hiệu quá mua (đắt). Rất hiệu quả khi thị trường đi ngang (Sideways).',
	N'MUA khi RSI vượt từ dưới lên trên mốc 30. BÁN khi RSI vượt từ trên xuống dưới mốc 70 hoặc khi đạt mục tiêu lợi nhuận.'
),
(
	N'MACD Cắt đường tín hiệu (MACD Signal Line Crossover)',
	N'Indicator',
	N'Đường trung bình động hội tụ phân kỳ (MACD) phản ánh xu hướng. Khi MACD cắt lên đường Tín hiệu, nó báo hiệu động lượng tăng giá bắt đầu.',
	N'MUA khi đường MACD cắt lên trên đường Signal Line trong xu hướng tăng (Uptrend). BÁN khi đường MACD cắt xuống dưới đường Signal Line.'
),
(
	N'Mô hình Hai đáy (Double Bottom Pattern)',
	N'ChartPattern',
	N'Mô hình đảo chiều xu hướng giảm sang tăng tạo bởi 2 đáy giá sàn bằng nhau. Sự bứt phá qua đường viền cổ (neckline) là tín hiệu mua mạnh mẽ.',
	N'MUA khi giá đóng cửa vượt lên trên đường viền cổ (Neckline) với khối lượng tăng mạnh.'
),
(
	N'Dải Bollinger co thắt và bứt phá (Bollinger Bands Squeeze & Breakout)',
	N'Indicator',
	N'Bollinger Bands thu hẹp báo hiệu thị trường sắp có biến động bùng nổ xu hướng mới.',
	N'MUA khi giá đóng cửa vượt lên trên Dải trên (Upper Band) sau một chu kỳ Bands co thắt cực đại.'
);
GO

-- =====================================================================
-- BƯỚC 4: TẠO BẢNG DỮ LIỆU AI (RIÊNG BIỆT - AI TRAINING DATA)
-- =====================================================================

-- Bảng vị thế giao dịch AI (HỌC TẬP/SIMULATION)
CREATE TABLE AiTradePositions (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Symbol NVARCHAR(MAX) NOT NULL,
	Quantity INT NOT NULL,
	EntryPrice DECIMAL(18,4) NOT NULL,
	ExitPrice DECIMAL(18,4) NULL,
	EntryDate DATETIME2 NOT NULL,
	ExitDate DATETIME2 NULL,
	Status NVARCHAR(MAX) NOT NULL,
	PnL DECIMAL(18,4) NOT NULL,
	StopLossPrice DECIMAL(18,4) NULL,
	TakeProfitPrice DECIMAL(18,4) NULL,
	TargetProfitAmount DECIMAL(18,4) NULL,
	InvestedAmount DECIMAL(18,4) NULL,
	BudgetAmount DECIMAL(18,4) NULL,
	ExpectedHoldDays INT NULL
);
GO

-- Bảng lệnh giao dịch AI
CREATE TABLE AiOrders (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Symbol NVARCHAR(MAX) NOT NULL,
	OrderType NVARCHAR(MAX) NOT NULL,
	Quantity INT NOT NULL,
	Price DECIMAL(18,4) NOT NULL,
	OrderDate DATETIME2 NOT NULL,
	Status NVARCHAR(MAX) NOT NULL,
	Rationale NVARCHAR(MAX) NULL
);
GO

-- Bảng chi tiết giao dịch AI (từng lệnh MUA/BÁN)
CREATE TABLE AiStockTransactions (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Symbol NVARCHAR(MAX) NOT NULL,
	TransactionType NVARCHAR(10) NOT NULL,
	Quantity INT NOT NULL,
	Price DECIMAL(18,4) NOT NULL,
	TransactionDate DATETIME2 NOT NULL,
	Fee DECIMAL(18,4) NULL,
	TotalAmount DECIMAL(18,4) NOT NULL DEFAULT 0,
	PnlAmount DECIMAL(18,4) NULL,
	Source NVARCHAR(50) NOT NULL DEFAULT 'AI_SIMULATION',
	PositionId INT NULL,
	Notes NVARCHAR(MAX) NULL,
	PriceHighSinceBuy DECIMAL(18,4) NULL,
	PriceLowSinceBuy DECIMAL(18,4) NULL,
	TimingScore DECIMAL(18,4) NULL
);
GO

-- Bảng bài học kinh nghiệm AI
CREATE TABLE AiTradeEpisodes (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	MarketContext NVARCHAR(MAX) NOT NULL,
	ActionTaken NVARCHAR(MAX) NOT NULL,
	Rationale NVARCHAR(MAX) NOT NULL,
	Result NVARCHAR(MAX) NOT NULL,
	LessonLearned NVARCHAR(MAX) NOT NULL,
	Timestamp DATETIME2 NOT NULL
);
GO

-- =====================================================================
-- BƯỚC 5: TẠO BẢNG QUẢN LÝ MIGRATION (EF CORE)
-- =====================================================================
CREATE TABLE __EFMigrationsHistory (
	MigrationId NVARCHAR(150) PRIMARY KEY,
	ProductVersion NVARCHAR(32) NOT NULL
);
GO

-- =====================================================================
-- THÔNG TIN QUAN TRỌNG
-- =====================================================================
PRINT '✅ Database schema đã tạo thành công!';
PRINT '📊 Bảng NGƯỜI DÙNG (USER DATA):';
PRINT '   - Assets, Orders, TradePositions, TradeEpisodes, StockTransactions';
PRINT '📊 Bảng CẤU HÌNH & CHIẾN LƯỢC:';
PRINT '   - UserPreferences, TradingStrategies';
PRINT '🤖 Bảng AI (TRAINING/SIMULATION - riêng biệt):';
PRINT '   - AiTradePositions, AiOrders, AiStockTransactions, AiTradeEpisodes';
PRINT '⚠️  LƯU Ý: Dữ liệu NGƯỜI DÙNG và AI hoàn toàn tách riêng!';
PRINT '💾 Bảng EF CORE Migration History: __EFMigrationsHistory';
GO
