using System;
using System.ComponentModel.DataAnnotations;

namespace AITradingSystem.Models
{
    public class TradingStrategy
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; } = string.Empty;

        [Required]
        public string StrategyType { get; set; } = string.Empty;

        [Required]
        public string Description { get; set; } = string.Empty;

        [Required]
        public string RuleLogic { get; set; } = string.Empty;

        public bool IsAutoGenerated { get; set; } = false;

        public int LearnCount { get; set; } = 0;

        public int WinCount { get; set; } = 0;

        public int LossCount { get; set; } = 0;

        public DateTime? LastLearnedAt { get; set; }
    }
}
